version: '3'

services:

  db:
    image: postgres
  web:
    build: .
    image: gabrieldeoliveiraestevam/projetofinal2_web
    command: chmod +x run_web.sh
    command: ./run_web.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    environment:
      - DJANGO_SETTINGS_MODULE=projeto.settings
      - RDS_DB_NAME=postgres
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=''
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
  