# Generated by Django 2.0.9 on 2018-11-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.IntegerField(blank=True, default=0, verbose_name='Tipo de Produto')),
                ('id_cliente', models.IntegerField(verbose_name='Id do Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Incluido em')),
            ],
            options={
                'verbose_name_plural': 'Demandas',
                'verbose_name': 'Demanda',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.IntegerField(blank=True, default=0, verbose_name='Tipo de Produto')),
                ('texto', models.TextField(blank=True, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'verbose_name': 'Mensagem',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email.Mensagem', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'verbose_name': 'Transação',
            },
        ),
    ]
